server:
	port: 8022
spring:
	application:
		name: menu
	datasource:
		username: root
		password: 123456
		driver: com.mysql.cj.jdbc.Driver
		url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
eureak:
	client:
		service-url:
			defaultZone: http://localhost:8762/eureka/
mybatis-plus:
	mapper-locations:classpath**/mapper/**.xml
		
